server:
  port: 17001
spring:
  datasource:
    url: jdbc:mysql://150.158.169.154:3306/practice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: Huanghong1314...
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小
      initial-size: 5
      #回收空闲连接时，将保证至少有minIdle个连接
      min-idle: 5
      #连接池中最多支持多少个活动会话
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #检查池中的连接是否仍可用的 SQL 语句,druid会连接到数据库执行该SQL, 如果正常返回，则表示连接可用，否则表示连接不可用
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      #程序 申请 连接时,进行连接有效性检查（低效，影响性能）
      test-on-borrow: false
      #程序 返还 连接时,进行连接有效性检查（低效，影响性能）
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #每个连接最多缓存多少个SQL
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙  日志 log4j
      #监控统计: filter:stat
      #日志监控: filter:log4j 或者 slf4j
      #防御SQL注入: filter:wall
      filters: stat,wall,slf4j
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: huang
        login-password: Huanghong1314...
mybatis:
  #mybatis没有默认值
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.huang.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
